import Head from "next/head";
import Bio from "../components/Bio";
import Post from "../components/Post";
import PostForm from "../components/PostForm";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Bio
          headshot="https://pbs.twimg.com/profile_images/968620685395308544/tCKxhH3N_400x400.jpg"
          name="Frankie Valentine"
          tagline="Building the next-gen of the web"
          role="Founder @ V3 Digital Studio"
        />
        <ul className={styles.posts}>
          <li>
            <Post
              content="I’m working in Figma to design a website to display all of my
              Tweets"
              date="4/28/2021"
            />
          </li>
          <li>
            <Post
              content="I’m working in Figma to design a website to display all of my
              Tweets"
              date="4/28/2021"
            />
          </li>
          <li>
            <Post
              content="I’m working in Figma to design a website to display all of my
              Tweets"
              date="4/28/2021"
            />
          </li>
        </ul>

        <PostForm />
      </main>
    </div>
  );
}
